sudo: true
language: java
jdk: openjdk8
stages:
- name: build
  if: branch = new-iofog-agent
- name: package_build
  if: branch = new-iofog-agent

jobs:
  include:
  - stage: build
    if: type IN (pull_request)
  - stage: package_build
    if: type IN (push)
    before_install:
    - sudo apt-get install sshpass xml-twig-tools
    script:
    - if [ "$TRAVIS_BRANCH" == "dev_package" ]; then export DEV=-dev; fi
    - export VERSION=`xml_grep 'version' pom.xml --text_only`
    - mvn clean install
    - sshpass -p $STAGE_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP "rm -rf /iofog-packaging-rpm/*; rm -rf /iofog-packaging/*;"
    - sshpass -p $STAGE_MACHINE_PASSWORD scp -o StrictHostKeyChecking=no -r iofog-packaging-rpm/*
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/iofog-packaging-rpm/
    - sshpass -p $STAGE_MACHINE_PASSWORD scp -r iofog-packaging/*
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/iofog-packaging/
    - sshpass -p $STAGE_MACHINE_PASSWORD scp daemon/target/iofog-daemon-jar-with-dependencies.jar
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/iofog-packaging/usr/bin/iofogd.jar
    - sshpass -p $STAGE_MACHINE_PASSWORD scp client/target/iofog-client-jar-with-dependencies.jar
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/iofog-packaging/usr/bin/iofog.jar
    - sshpass -p $STAGE_MACHINE_PASSWORD scp daemon/target/iofog-daemon-jar-with-dependencies.jar
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/iofog-packaging-rpm/usr/bin/iofogd.jar
    - sshpass -p $STAGE_MACHINE_PASSWORD scp client/target/iofog-client-jar-with-dependencies.jar
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/iofog-packaging-rpm/usr/bin/iofog.jar
    - sshpass -p $STAGE_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP "cd /iofog-packaging; fpm -s dir -t deb -n \"iofog-agent${DEV}\" 
      -v $VERSION -a all --deb-no-default-config-files --after-install debian.sh --after-remove remove.sh --before-upgrade 
      upgrade.sh --after-upgrade debian.sh etc usr; package_cloud push iofog/iofog-agent/ubuntu/precise 
      iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push iofog/iofog-agent/ubuntu/trusty iofog-agent${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/iofog-agent/ubuntu/utopic iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push 
      iofog/iofog-agent/ubuntu/vivid iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push iofog/iofog-agent/ubuntu/wily 
      iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push iofog/iofog-agent/ubuntu/xenial iofog-agent${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/iofog-agent/ubuntu/bionic iofog-agent${DEV}_${VERSION}_all.deb;
      package_cloud push iofog/iofog-agent/debian/wheezy iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push 
      iofog/iofog-agent/debian/jessie iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push iofog/iofog-agent/debian/stretch 
      iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push iofog/iofog-agent/debian/buster iofog-agent${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/iofog-agent/raspbian/wheezy iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push 
      iofog/iofog-agent/raspbian/jessie iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push iofog/iofog-agent/raspbian/stretch 
      iofog-agent${DEV}_${VERSION}_all.deb; package_cloud push iofog/iofog-agent/raspbian/buster iofog-agent${DEV}_${VERSION}_all.deb; 
      cd /iofog-packaging-rpm; fpm -s dir -t rpm -n \"iofog-agent${DEV}\" -v $VERSION -a all --rpm-os 'linux' 
      --after-install rpm.sh --after-remove remove.sh --before-upgrade upgrade.sh --after-upgrade rpm.sh etc usr; 
      package_cloud push iofog/iofog-agent/fedora/22 iofog-agent${DEV}-${VERSION}-1.noarch.rpm; package_cloud 
      push iofog/iofog-agent/fedora/23 iofog-agent${DEV}-${VERSION}-1.noarch.rpm; package_cloud push iofog/iofog-agent/fedora/24 
      iofog-agent${DEV}-${VERSION}-1.noarch.rpm; package_cloud push iofog/iofog-agent/fedora/25 
      iofog-agent${DEV}-${VERSION}-1.noarch.rpm; package_cloud push iofog/iofog-agent/fedora/26 
      iofog-agent${DEV}-${VERSION}-1.noarch.rpm; package_cloud push iofog/iofog-agent/fedora/27 
      iofog-agent${DEV}-${VERSION}-1.noarch.rpm; package_cloud push iofog/iofog-agent/fedora/28 
      iofog-agent${DEV}-${VERSION}-1.noarch.rpm; package_cloud push iofog/iofog/el/6 iofog-agent${DEV}-${VERSION}-1.noarch.rpm; package_cloud push iofog/iofog-agent/el/7 iofog-agent${DEV}-${VERSION}-1.noarch.rpm"
