sudo: true
language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.cache"
notifications:
  email: false
  slack:
    rooms:
      secure: taYfHvkkrx/6FbL2FURMvYuu2vUB9thEK2qIo4DZPOzlwdn5XpqzAFmMXD1kCqDLTPGnhsGknbqkx+zMWIjLg3RCsxNm+yPik98QO9NCMu9L+gjEmxt31m/WGfYyCQ0Gf1/cxvxtrC/TK5T1GzF6XKsRExmDctOexwWJIBnFLP77LbWhKKe3F8DAWtzs8NwEsNGgovbhnqT3RMcymfmdWYyel2cheev79+G1EX0tPar76cAb3fBBHIi+TDeek5BEhcofoFFyBJDFQhTVZ/rImhCT8ilNAA9Eq5JWc2MY9UdYBclIVsNPXmqc9XQyU9LcQu8HjfO/afgZvG727kJCOU0UpM3u8LWHx/TxUqXQ7hspR5V0FdDxe9bvARzyMDtmgjWUracG45E9uwtANYSpv4iC+LchAoF9/9ACDN13ubAYBlS6WB6NbwlH2OwVf4IAsu52WCOntT/lvECnDB7Lo01hEu8cd8D64So6ftmokdehfGdhzLf6Ngg0YzfD3nS1ULmwKz0ytHeSJRSbXUdP/1XoEbp1/RaJVMauEoRDh34GEORh5brsBZ5f66C/O4caiYbpgrRLUMGDxHqD5ujKg0U809KG9suJf26eoErjzUDHRsQOg/6PxvpCPZBmi34hAh39W17jiea/C0DLTFdMEaCj7dqfwihr+pr0dtZlox0=
    on_success: change
    on_failure: always
stages:
- name: build
  if: branch = develop
- name: package_build
  if: branch IN (master, dev_package)
- name: deploy
  if: branch IN (master, dev_package)

jobs:
  include:
  - stage: build
    before_install:
    - sudo apt-get install sshpass
    script:
    - sshpass -p $DEV_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no -p $DEV_MACHINE_PORT
      $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP "sudo service iofog stop; sudo rm -rf
      /usr/bin/iofogd_bckp.jar /usr/bin/iofog_bckp.jar; sudo mv /usr/bin/iofogd.jar
      /usr/bin/iofogd_bckp.jar; sudo mv /usr/bin/iofog.jar /usr/bin/iofog_bckp.jar"
    - sshpass -p $DEV_MACHINE_PASSWORD scp -P $DEV_MACHINE_PORT daemon/target/iofog-daemon-jar-with-dependencies.jar
      $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP:/home/owner/iofogd.jar
    - sshpass -p $DEV_MACHINE_PASSWORD scp -P $DEV_MACHINE_PORT client/target/iofog-client-jar-with-dependencies.jar
      $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP:/home/owner/iofog.jar
    - sshpass -p $DEV_MACHINE_PASSWORD ssh -p $DEV_MACHINE_PORT $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP
      "sudo cp /home/owner/iofogd.jar /usr/bin/; sudo cp /home/owner/iofog.jar /usr/bin/;
      sudo rm -rf /home/owner/iofogd.jar /home/owner/iofog.jar; sudo service iofog
      start"
  - stage: package_build
    if: branch = dev_package
    env: DEV=-dev
    before_install:
    - sudo apt-get install ruby ruby-dev rubygems-integration build-essential
    install:
    - sudo gem install --no-ri --no-rdoc fpm
    script:
    - cp target/iofog-daemon-jar-with-dependencies.jar iofog-packaging/usr/bin/iofogd.jar
    - cp target/iofog-client-jar-with-dependencies.jar iofog-packaging/usr/bin/iofog.jar
    - cp target/iofog-daemon-jar-with-dependencies.jar iofog-packaging-rpm/usr/bin/iofogd.jar
    - cp target/iofog-client-jar-with-dependencies.jar iofog-packaging-rpm/usr/bin/iofog.jar
    - cd iofog-packaging
    - fpm -s dir -t deb -n "iofog${DEV}" -v $VERSION -a all --deb-no-default-config-files
      --after-install debian.sh etc usr var
    - cd ../iofog-packaging-rpm
    - fpm -s dir -t rpm -n "iofog${DEV}" -v $VERSION -a all --rpm-os 'linux' --after-install
      rpm.sh etc usr var
  - stage: deploy
    script: skip
    env:
    - OS=ubuntu DIST=precise FOLDER=iofog-packaging EXTENSION=deb
    - OS=ubuntu DIST=trusty FOLDER=iofog-packaging EXTENSION=deb
    - OS=ubuntu DIST=utopic FOLDER=iofog-packaging EXTENSION=deb
    - OS=ubuntu DIST=vivid FOLDER=iofog-packaging EXTENSION=deb
    - OS=ubuntu DIST=wily FOLDER=iofog-packaging EXTENSION=deb
    - OS=ubuntu DIST=xenial FOLDER=iofog-packaging EXTENSION=deb
    - OS=debian DIST=wheezy FOLDER=iofog-packaging EXTENSION=deb
    - OS=debian DIST=jessie FOLDER=iofog-packaging EXTENSION=deb
    - OS=debian DIST=stretch FOLDER=iofog-packaging EXTENSION=deb
    - OS=debian DIST=buster FOLDER=iofog-packaging EXTENSION=deb
    - OS=raspbian DIST=wheezy FOLDER=iofog-packaging EXTENSION=deb
    - OS=raspbian DIST=jessie FOLDER=iofog-packaging EXTENSION=deb
    - OS=raspbian DIST=stretch FOLDER=iofog-packaging EXTENSION=deb
    - OS=raspbian DIST=buster FOLDER=iofog-packaging EXTENSION=deb
    - OS=fedora DIST=22 FOLDER=iofog-packaging-rpm EXTENSION=rpm
    - OS=fedora DIST=23 FOLDER=iofog-packaging-rpm EXTENSION=rpm
    - OS=fedora DIST=24 FOLDER=iofog-packaging-rpm EXTENSION=rpm
    - OS=el DIST=7 FOLDER=iofog-packaging-rpm EXTENSION=rpm
    - OS=el DIST=6 FOLDER=iofog-packaging-rpm EXTENSION=rpm
    deploy:
    - provider: packagecloud
      repository: "${PACKAGECLOUD_REPO}"
      username: "${PACKAGECLOUD_USERNAME}"
      token: "${PACKAGECLOUD_TOKEN}"
      dist: "${OS}/${DIST}"
      package_glob: "${FOLDER}/*.${EXTENSION}"
      on:
        condition: -n "${OS}" && -n "${DIST}" && -n "${FOLDER}" && -n "${EXTENSION}"
